service: workflow-lambda

frameworkVersion: "3"

useDotenv: true

plugins:
    - serverless-offline
    - serverless-esbuild


custom:
  stage: ${opt:stage, 'dev'}
  esbuild:
    bundle: true
    minify: false

provider:
    name: aws
    stage: ${self:custom.stage}
    timeout: 15
    runtime: nodejs18.x
    region: us-east-1
    deploymentBucket:
      name: workflow-lambda-dev-serverlessdeploymentbucket-kkydemn5hkgz
    environment:
        BUCKET_NAME: ${env:BUCKET_NAME}
        BUCKET_FOLDER_NAME: ${env:BUCKET_FOLDER_NAME}      
        # COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}
        # COGNITO_POOL_ID: ${env:COGNITO_POOL_ID}

functions: 
    - ${file(./project/function.yml)}
    - ${file(./workflow/function.yml)}
    - ${file(./usecase/function.yml)}
    - ${file(./dashboard/function.yml)}
    - ${file(./task/function.yml)}
    - ${file(./resource/function.yml)}

# custom:
#   http:
#     cors:
#       origin: '*' # Allow requests from any origin
#       methods: ['OPTIONS', 'POST', 'PUT']    